### ISSUE TITLE
modular dir error

### ISSUE THREAD

**Issue by SuperAdam47** [HonorGamerHD/ReportSystem#2]
![Ekran Alıntısısd](https://user-images.githubusercontent.com/16169771/62414940-dcc09100-b62a-11e9-9e71-a9b52712ed1e.PNG)

**Comment by HonorGamerHD** [comment]
Hmmm did u changed to global mode?

**Comment by HonorGamerHD** [comment]
And when did this error occur?

**Comment by StrawberryNature** [comment]
have the same error, was from dev release 10

**Comment by HonorGamerHD** [comment]
At plugin start up?

**Comment by StrawberryNature** [comment]
yes letter

**Comment by HonorGamerHD** [comment]
Hmm ok

**Comment by HonorGamerHD** [comment]
Test with latest build again: https://poggit.pmmp.io/ci/HonorGamerHD/ReportSystem/ReportSystem

**Comment by StrawberryNature** [comment]
Unfortunately, I still get the same output

**Comment by HonorGamerHD** [comment]
Rip let me test this my self

**Comment by StrawberryNature** [comment]
![Screenshot_20190803_194717](https://user-images.githubusercontent.com/47510788/62415287-9f0e3900-b627-11e9-98a9-3ac45db07c8c.jpg)

**Comment by HonorGamerHD** [comment]
@StrawberryNature  wich mode did u use? local or global?

**Comment by StrawberryNature** [comment]
what do you mean exactly?

**Comment by HonorGamerHD** [comment]
@StrawberryNature try [this one](https://poggit.pmmp.io/r/63784/ReportSystem_dev-13.phar)

**Comment by StrawberryNature** [comment]
it can now start

**Comment by HonorGamerHD** [comment]
good! so thanks for reporting this issue and dont forget to leave a star :D

**Comment by StrawberryNature** [comment]
that comes when I go to report list with / reportadm and then want to see the new report
![Screenshot_20190803_201735](https://user-images.githubusercontent.com/47510788/62415552-eb5b7800-b62b-11e9-8283-c0c33cb2f66b.jpg)
