### ISSUE TITLE
problems with reportlist

### ISSUE THREAD

**Issue by StrawberryNature** [HonorGamerHD/ReportSystem#3]
that comes when I go to report list with / reportadm and then want to see the new report
![Screenshot_20190803_201735](https://user-images.githubusercontent.com/47510788/62415884-683d2080-b631-11e9-9ab1-a5448f4e6644.jpg)

**Comment by HonorGamerHD** [comment]
Send me screenshot of ur config.yml

**Comment by StrawberryNature** [comment]
is default settings

**Comment by HonorGamerHD** [comment]
Hmm

**Comment by StrawberryNature** [comment]
I have my server at minehub.de, which setting is required local or global?

**Comment by HonorGamerHD** [comment]
Fixed now, try new build

**Comment by HonorGamerHD** [comment]
I edited on mobile, hopefully it works lol

**Comment by StrawberryNature** [comment]
okay i do

**Comment by StrawberryNature** [comment]
cool I get the message when join.  only I have the problem that I can not delete the reports ...
![Screenshot_20190803_212956](https://user-images.githubusercontent.com/47510788/62416171-e69bc180-b635-11e9-986c-5df3c3b832f2.jpg)

**Comment by StrawberryNature** [comment]
I also tried to delete all at once, message I got this happened, only if I then do / reportlist I see the reports yet.

**Comment by HonorGamerHD** [comment]
Ur errors are weird, never got them lol but i try To fix them all

**Comment by StrawberryNature** [comment]
may also be that my translation is not correct.

**Comment by HonorGamerHD** [comment]
I fixed move and delete bug, u should test again

**Comment by HonorGamerHD** [comment]
Np i understand u

**Comment by StrawberryNature** [comment]
So you understand my problem?

**Comment by HonorGamerHD** [comment]
Yes, ill fixed that delete big

**Comment by HonorGamerHD** [comment]
Maybe u should try to do it again and see what happen with my updated version. Im at mobile now and i cant test

**Comment by StrawberryNature** [comment]
Thanks it works now without problems <3

**Comment by HonorGamerHD** [comment]
Yeee, if u have any other problems let me know them. Dont forget to leave a star :D

**Comment by StrawberryNature** [comment]
my star you have long ^ ^

**Comment by HonorGamerHD** [comment]
U speak Herman german right? 🤔

**Comment by StrawberryNature** [comment]
yes

**Comment by HonorGamerHD** [comment]
Ok me too xD

**Comment by StrawberryNature** [comment]
ja wiso dann so schwer

**Comment by HonorGamerHD** [comment]
Bc englische bois verstehen kein deutsch und können so prüfen ob es diesen Fehler schon gegeben hat, schreib mir mal per Discord: ImNotYourDev#1487

**Comment by StrawberryNature** [comment]
ok ja gerne
