### ISSUE TITLE
Add Exit/remove buttons

### ISSUE THREAD

**Issue by StrawberryNature** [HonorGamerHD/ReportSystem#4]
it would be nice if you could add an exit button at / report.  
also with / reportadmin a back button could add recycle bin and reportlist.  
also with / reportadmin an exit button would also be nice, so you do not have to hit the little X.

**Comment by HonorGamerHD** [comment]
Next version is release version, after that version i add more features and creating addon plugins.

**Comment by StrawberryNature** [comment]
omg nice thx yu ^^

**Comment by mikeygio10** [comment]
also if you could please add diffrent perms for /reportlist and /reportadmin

**Comment by mikeygio10** [comment]
cooldown so player cant spam reports

**Comment by HonorGamerHD** [comment]
thx for review my plugin, i add those features today. :D

**Comment by HonorGamerHD** [comment]
@StrawberryNature i added exit and back buttons, try latest build.

@mikeygio10 i added extra permission for list command, cooldown is following next changes. try latest build

**Comment by StrawberryNature** [comment]
cool as everything works thank you for this update.
